import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div id='navbar'>
          <Link id="home" className="nv" href="../">홈      </Link>
          <Link id="news" className='nv' href="../news">뉴스      </Link>
          <Link id="rule" className='nv' href="../rule">규칙      </Link>
        </div>
        {children}
      </body>
      
    </html>
  )
}
